# Generated by Django 2.0.5 on 2018-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='first_payer',
            new_name='first_player',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player to move'), ('S', 'Second Player to move'), ('W', 'First Player wins'), ('L', 'Second Player wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
